import type { Metadata } from 'next';
import { Providers } from './providers';
import { inter, satisfy } from '@/components/fonts';
import './globals.css';
import NavBar from '@/components/nav-bar/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning className={`${inter.variable} ${satisfy.variable}`}>
      <body className='min-h-svh font-inter'>
        <Providers>
          <NavBar />
          <main className='container'>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
